version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodie-express-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    expose:
      - "5000"
    volumes:
      - ./logs:/app/logs
    networks:
      - foodie-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: foodie-express-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - foodie-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  foodie-network:
    driver: bridge

volumes:
  nginx-logs:
